federation_version: =2.11.0
subgraphs:
  auth:
    routing_url: http://localhost:4010/graphql
    schema:
      file: src/subgraphs/auth/schema.graphql
  user:
    routing_url: http://localhost:4020/graphql
    schema:
      file: src/subgraphs/user/user.schema.graphql
  booking:
    routing_url: http://localhost:4030/graphql
    schema:
      file: src/subgraphs/booking/schema.graphql
  review:
    routing_url: http://localhost:4040/graphql
    schema:
      file: src/subgraphs/review/schema.graphql
  payment:
    routing_url: http://localhost:4050/graphql
    schema:
      file: src/subgraphs/payment/schema.graphql
  tenant:
    routing_url: http://localhost:4060/graphql
    schema:
      file: src/subgraphs/tenant/tenant.schema.graphql
  audit:
    routing_url: http://localhost:4070/graphql
    schema:
      file: src/subgraphs/audit/schema/schema.graphql
  location:
    routing_url: http://localhost:4080/graphql
    schema:
      file: src/subgraphs/location/schema.graphql
  amenity:
    routing_url: http://localhost:4090/graphql
    schema:
      file: src/subgraphs/amenity/schema.graphql
  listing:
    routing_url: http://localhost:4101/graphql
    schema:
      file: src/subgraphs/listing/schema.graphql
  account:
    routing_url: http://localhost:4102/graphql
    schema:
      file: src/subgraphs/account/schema.graphql
  cart:
    routing_url: http://localhost:4103/graphql
    schema:
      file: src/subgraphs/cart/schema.graphql
  wisdom:
    routing_url: http://localhost:4200/graphql
    schema:
      file: src/wisdom/schemas/schema.graphql
