// src/wisdom/shared/enums/action.enum.ts

export enum AgentAction {
  // Listing
  OPTIMIZE_TITLE = "OPTIMIZE_TITLE",
  OPTIMIZE_PRICE = "OPTIMIZE_PRICE",
  OPTIMIZE_CATEGORY = "OPTIMIZE_CATEGORY",
  OPTIMIZE_LISTING = "OPTIMIZE_LISTING",
  OPTIMIZE_DESCRIPTION = "OPTIMIZE_DESCRIPTION",
  SEO_ANALYSIS = "SEO_ANALYSIS",
  GET_LISTING = "GET_LISTING",
  SEARCH_LISTING = "SEARCH_LISTING",
  CHECK_AVAILABILITY = "CHECK_AVAILABILITY",

  // Booking
  CREATE_BOOKING = "CREATE_BOOKING",
  CANCEL_BOOKING = "CANCEL_BOOKING",
  CONFIRM_BOOKING = "CONFIRM_BOOKING",
  COMPLETE_BOOKING = "COMPLETE_BOOKING",
  MODIFY_BOOKING = "MODIFY_BOOKING",
  GET_BOOKING = "GET_BOOKING",
  GET_MY_BOOKINGS = "GET_MY_BOOKINGS",
  CHECK_IN_DATE = "CHECK_IN_DATE",
  CHECK_OUT_DATE = "CHECK_OUT_DATE",
  CUSTOMER_COUNT = "CUSTOMER_COUNT",
  
  // General
  GENERAL = "GENERAL",
  GET_LATEST_BOOKING = "GET_LATEST_BOOKING",
}
