//src/modules/tokens/ai.tokens.ts
export const TOKENS_AI = {

  tool: {
    rewriteDescriptionTool: Symbol.for("RewriteDescriptionTool"),
    rewriteTitleTool: Symbol.for("RewriteTitleTool"),
    analyzeListingTool: Symbol.for("AnalyzeListingTool"),
    listingOptimizationTool: Symbol.for("ListingOptimizationTool"),
    generateSEOKeywordsTool: Symbol.for("GenerateSEOKeywordsTool"),
    priceOptimizationTool: Symbol.for("PriceOptimizationTool"),
    categoryOptimizationTool: Symbol.for("CategoryOptimizationTool"),
    bookingOptimizationTool: Symbol.for("BookingOptimizationTool"),
    fraudDetectionTool: Symbol.for("FraudDetectionTool"),
    anomalyDetectionTool: Symbol.for("AnomalyDetectionTool"),
    paymentRiskScoringTool: Symbol.for("PaymentRiskScoringTool"),
    reviewAnalysisTool: Symbol.for("ReviewAnalysisTool"),
    sentimentAnalysisTool: Symbol.for("SentimentAnalysisTool"),
    contentModerationTool: Symbol.for("ContentModerationTool"),
    reviewValidationTool: Symbol.for("ReviewValidationTool"),
    reviewReplyTool: Symbol.for("ReviewReplyTool"),
    reviewReportTool: Symbol.for("ReviewReportTool"),
    bookingFraudTool: Symbol.for("BookingFraudTool"),
  },
  agent: {
    listingOptimizationAgent: Symbol.for("ListingOptimizationAgent"),
    bookingOptimizationAgent: Symbol.for("BookingOptimizationAgent"),
    bookingFraudAgent: Symbol.for("BookingFraudAgent"),
    paymentRiskAgent: Symbol.for("PaymentRiskAgent"),
    reviewAnalysisAgent: Symbol.for("ReviewAnalysisAgent"),
  },

  usecase: {
    runListingAgentUseCase: Symbol.for("RunListingAgentUseCase"),
    runBookingAgentUseCase: Symbol.for("RunBookingAgentUseCase"),
    runPaymentAgentUseCase: Symbol.for("RunPaymentAgentUseCase"),
    runReviewAgentUseCase: Symbol.for("RunReviewAgentUseCase"),
    generateTitleSuggestionUseCase: Symbol.for("GenerateTitleSuggestionUseCase"),
    seoAnalysisUseCase: Symbol.for("SEOAnalysisUseCase"),
    priceOptimizationUseCase: Symbol.for("PriceOptimizationUseCase"),
    categoryOptimizationUseCase: Symbol.for("CategoryOptimizationUseCase"),
    bookingOptimizationUseCase: Symbol.for("BookingOptimizationUseCase"),
    fraudDetectionUseCase: Symbol.for("FraudDetectionUseCase"),
    anomalyDetectionUseCase: Symbol.for("AnomalyDetectionUseCase"),
    paymentRiskScoringUseCase: Symbol.for("PaymentRiskScoringUseCase"),
    reviewAnalysisUseCase: Symbol.for("ReviewAnalysisUseCase"),
    sentimentAnalysisUseCase: Symbol.for("SentimentAnalysisUseCase"),
    contentModerationUseCase: Symbol.for("ContentModerationUseCase"),
    reviewValidationUseCase: Symbol.for("ReviewValidationUseCase"),
    reviewReplyUseCase: Symbol.for("ReviewReplyUseCase"),
    reviewReportUseCase: Symbol.for("ReviewReportUseCase"),
    bookingFraudUseCase: Symbol.for("BookingFraudUseCase"),
    cancelBookingUseCase: Symbol.for("CancelBookingUseCase"),
    createBookingUseCase: Symbol.for("CreateBookingUseCase"),
    createReviewUseCase: Symbol.for("CreateReviewUseCase"),
  },
  acl: {
    reviewACL: Symbol.for("ReviewACL"),
  },
  OpenAIService: Symbol.for("OpenAIService"),
  OpenAIAdapter: Symbol.for("OpenAIAdapter"),
  ListingAISuggestionRepository: Symbol.for("ListingAISuggestionRepository"),
  ListingAISuggestionModel: Symbol.for("ListingAISuggestionModel"),

  repos: {
    bookingRepository: Symbol.for("BookingRepository"),
  paymentRepository: Symbol.for("PaymentRepository"),
  reviewRepository: Symbol.for("ReviewRepository"),
  cancelBookingRepository: Symbol.for("CancelBookingRepository"),
  },
  
}