// src/wisdom/memory/type/artifactType.ts
export enum MemoryArtifactType {
    LISTING_SEARCH_RESULT = "LISTING_SEARCH_RESULT",
    DATES_SELECTED = "DATES_SELECTED",
    GUEST_COUNT_SELECTED = "GUEST_COUNT_SELECTED",
    CONTACT_SET = "CONTACT_SET",
    SPECIAL_REQUEST_SET = "SPECIAL_REQUEST_SET",
    BOOKING_CREATED = "BOOKING_CREATED",
}

export enum ArtifactType {

    LISTING_SEARCH_RESULT = "LISTING_SEARCH_RESULT",

    DATES_SELECTED = "DATES_SELECTED",

    GUEST_COUNT_SELECTED = "GUEST_COUNT_SELECTED",

    CONTACT_SET = "CONTACT_SET",

    SPECIAL_REQUEST_SET = "SPECIAL_REQUEST_SET",

    BOOKING_CREATED = "BOOKING_CREATED",

    BOOKING_CANCELLED = "BOOKING_CANCELLED",
}