// src/security/actions.ts

export enum SecurityAction {
  CREATE_PUBLIC_LISTING = "CREATE_PUBLIC_LISTING",
  UPDATE_PUBLIC_LISTING = "UPDATE_PUBLIC_LISTING",
  DELETE_PUBLIC_LISTING = "DELETE_PUBLIC_LISTING",

  POST_REVIEW = "POST_REVIEW",
  SEND_MESSAGE = "SEND_MESSAGE",
}