name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service backend --project bb75c99e-082e-4f2f-b4d6-e2784b5759ac --environment production--detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
